<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function wsc_es_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wsc_es':
      $variables = [
        ':wsc_es' => Url::fromRoute('help.page', ['name' => 'wsc_es'])->toString(),
      ];

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href=":wsc_es">WebService Content for ElasticSearch</a> module provide features to pull and push indexes between Drupal instance and ElasticeSearch remote servers.', $variables) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('[to be completed]') . '</p>';

      return $output;
  }
}
