<?php

/**
 * @file
 * Xtended Content Elastica module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\xtc\XtendedContent\API\Config;

/**
 * Implements hook_help().
 */
function xtcelastica_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtcelastica':
      return Config::getHelp('xtcelastica');
  }
}

/**
 * Implements hook_node_save().
 */
function xtcelastica_node_save(NodeInterface $node, array $values){

}

/**
 * Implements hook_node_view().
 */
function xtcelastica_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
//  dump($entity);
}

